version: '3'

vars:
  FUNCS_DIR: 'funcs'
  TARGET: 'wasm32-unknown-unknown'
  FLAGS: '--release --target {{.TARGET}}'

tasks:
  build *:
    vars:
      FUNC: '{{index .MATCH 0}}'
    cmds:
      - cd {{.FUNCS_DIR}}/{{.FUNC}} && cargo build {{.FLAGS}}

  cbuild *:
    vars:
      FUNC: '{{index .MATCH 0}}'
    cmds:
      - cd {{.FUNCS_DIR}}/{{.FUNC}} && clang22 -O2 --target=wasm32 -mcpu=mvp -nostdinc -nostdlib -Wl,--no-entry -Wl,--export=addr_ips -Wl,--export=sum_get -Wl,--export=array_get -Wl,--export=filter_ips sum_mem.c -o sum_mem.wasm

  header *:
    vars:
      FUNC: '{{index .MATCH 0}}'
    cmds:
      - cd {{.FUNCS_DIR}}/{{.FUNC}}/target/{{.TARGET}}/release && xxd -i {{.FUNC}}.wasm > ../../../../../{{.FUNC}}.h
  
  cheader *:
    vars:
      FUNC: '{{index .MATCH 0}}'
    cmds:
      - cd {{.FUNCS_DIR}}/{{.FUNC}} && xxd -i {{.FUNC}}.wasm > ../../{{.FUNC}}.h

  load:
    cmds:
      - sudo make load
    silent: true

  unload:
    cmds:
      - sudo make unload
    silent: true

  default:
    cmds:
      - task unload
      - make
    silent: true
